<?php

namespace Database\Seeders\Auth;

use Illuminate\Database\Seeder;
use App\Models\Auth\Role;
use App\Models\Auth\Permission;
use App\Models\Auth\RolePermission;

class RolePermissionSeeder extends Seeder
{
    /**
     * Permission keys are auto-generated by PermissionSeeder as:
     * strtolower(module_name) . '.' . strtolower(action)
     *
     * Available modules: leads, enrollment, academic, attendance, financial, reports, hr, notifications
     * Available actions: view, create, edit, delete, approve, override
     */
    public function run(): void
    {
        $rolePermissions = [

            // Admin gets everything — assigned dynamically from DB
            'Admin' => '*',

            // CS: manage leads + registration + financials + outstanding
            'Customer Service' => [
                'leads.view',
                'leads.create',
                'leads.edit',
                'leads.delete',
                'enrollment.view',
                'enrollment.create',
                'financial.view',
                'financial.create',
                'notifications.view',
            ],

            // Student Care: scheduling, enrollment, attendance oversight
            'Student Care' => [
                'enrollment.view',
                'enrollment.create',
                'enrollment.edit',
                'academic.view',
                'academic.create',
                'academic.edit',
                'attendance.view',
                'attendance.edit',
                'financial.view',
                'notifications.view',
            ],

            // Teacher: view schedule + take attendance + submit reports
            'Teacher' => [
                'academic.view',
                'attendance.view',
                'attendance.create',
                'attendance.edit',
                'reports.view',
                'reports.create',
                'reports.edit',
            ],

            // Student: view only
            'Student' => [
                'academic.view',
                'attendance.view',
                'reports.view',
            ],
        ];

        foreach ($rolePermissions as $roleName => $permissions) {

            $role = Role::where('role_name', $roleName)->first();

            if (!$role) {
                $this->command->warn("Role '{$roleName}' not found — skipping.");
                continue;
            }

            // Admin: give all permissions in DB
            if ($permissions === '*') {
                $allIds = Permission::pluck('permission_id')->toArray();
                foreach ($allIds as $permissionId) {
                    RolePermission::firstOrCreate([
                        'role_id'       => $role->role_id,
                        'permission_id' => $permissionId,
                    ]);
                }
                $this->command->info("Admin: assigned all " . count($allIds) . " permissions.");
                continue;
            }

            // Other roles: assign by permission_key
            foreach ($permissions as $permissionKey) {
                $permission = Permission::where('permission_key', $permissionKey)->first();

                if (!$permission) {
                    $this->command->warn("Permission '{$permissionKey}' not found in DB — skipping.");
                    continue;
                }

                RolePermission::firstOrCreate([
                    'role_id'       => $role->role_id,
                    'permission_id' => $permission->permission_id,
                ]);
            }

            $this->command->info("{$roleName}: permissions assigned.");
        }
    }
}